### PR TITLE
mark animation

### PR DESCRIPTION
**Pull request by markmanalo34**
created gif background animation

### CODE REVIEW

**Review by amiedawn — COMMENTED** [review]
So does the giphy replace the background or go over it somewhere?

**Comment by joe-riley** [comment]
I think this will be ok for our demo today but maybe for the final project we can choose a gif that has a higher resolution and is a bit more subtle- maybe one without a watermark. Also, I think I misunderstood what animation meant in this context. I thought there was going to be some kind of movement of elements using CSS when this is replacing the background with a gif.

**Comment by ghost** [comment]
adding slack message from mark

'Hey James I got some animation ideas put together but I think it should only be added to our final project'

**Comment by ghost** [comment]
closed

**Pull request closed without merging**
